sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker/docker-compose.yml build --no-cache
  - docker-compose -f docker/docker-compose.yml up -d; sleep 5;
  - mv -f .env.travis .env
  - docker exec basicrum_bo_php composer install
  - docker exec basicrum_bo_php php bin/console c:c
  - docker exec basicrum_bo_php php bin/console cache:clear

script: 
  - |
    loop=0; 
    while [ -z "$(docker exec basicrum_bo_php /bin/console doctrine:migrations:migrate --no-interaction)" ]; do
      if["$loop" -gt 9 ]; then
        break
      fi;
      echo 'Waiting for MySql to start ...' && sleep 2;
      ((loop++))
    done;

  - |
    for n in {1..5}; do \
    docker exec basicrum_bo_php bin/console basicrum:beacon:init-folders; \ 
    docker exec basicrum_bo_php bin/console basicrum:beacon:archive-bundle; \
    docker exec basicrum_bo_php bin/console basicrum:beacon:bundle-raw; \
    docker exec basicrum_bo_php bin/console basicrum:beacon:import-bundle; \
    docker exec basicrum_bo_php bin/console basicrum:cache:clean; \
    docker exec basicrum_bo_php bin/console basicrum:last-blocking-resource:calculate; \
    docker exec basicrum_bo_php bin/console basicrum:visit:generate; \
    done;

  - docker exec -it basicrum_bo_php php bin/phpunit
